// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg_IWY5IEtWC0g9MdhJS561mSeFQDsjtQ',
    appId: '1:626169085990:web:b8df78a68528d62bb626e7',
    messagingSenderId: '626169085990',
    projectId: 'glwa-app',
    authDomain: 'glwa-app.firebaseapp.com',
    storageBucket: 'glwa-app.appspot.com',
    measurementId: 'G-CZEPJ8VH7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUg6fDkFyVajfiuK_XWSwNgbOW1K7aMFA',
    appId: '1:626169085990:android:f780cca42132234ab626e7',
    messagingSenderId: '626169085990',
    projectId: 'glwa-app',
    storageBucket: 'glwa-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLP310ggJcLeq51PD-o7W5738utvTeio',
    appId: '1:626169085990:ios:e296093ec4241911b626e7',
    messagingSenderId: '626169085990',
    projectId: 'glwa-app',
    storageBucket: 'glwa-app.appspot.com',
    iosBundleId: 'com.example.microbialSourceTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFLP310ggJcLeq51PD-o7W5738utvTeio',
    appId: '1:626169085990:ios:64ea9b27fc6d0d4eb626e7',
    messagingSenderId: '626169085990',
    projectId: 'glwa-app',
    storageBucket: 'glwa-app.appspot.com',
    iosBundleId: 'com.example.microbialSourceTracking.RunnerTests',
  );
}
